name: Ephemeral Infra Deletion

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Destroy Expired Infra
        run: |

          chmod +x live/scripts/aws-cleanup-script.sh

          cd live/scripts

          ./aws-cleanup-script.sh