name: Ephemeral Infra Creation

on:
  workflow_dispatch:
    inputs:
      template:
        description : "Select Template"
        required : true
        type : choice
        options:
          - dev
          - staging
          - prod
      request_id:
        description: "Unique request ID"
        required: true
      ttl_seconds:
        description: "TTL in seconds"
        required: true
      owner:
        description: "Owner name"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      REQUEST_ID: ${{ github.event.inputs.request_id }}
      TTL_SECONDS: ${{ github.event.inputs.ttl_seconds }}
      OWNER: ${{ github.event.inputs.owner }}

    permissions:
      contents: write 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate TTL
        run: |
          if ! [[ "${{ github.event.inputs.ttl_seconds }}" =~ ^[0-9]+$ ]]; then
            echo "TTL must be a number"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Create Request Directory from template
        run: |

          TEMPLATE=${{github.event.inputs.template}}
          REQUEST_ID=${{github.event.inputs.request_id}} 

          TEMPLATE_PATH="live/ephemeral/sandbox/template/$TEMPLATE"
          REQUEST_PATH="live/ephemeral/sandbox/requests/$REQUEST_ID"

          if [ -d "$REQUEST_PATH" ]; then
            echo "Request ID already exists!"
            exit 1
          fi
          cp -r $TEMPLATE_PATH $REQUEST_PATH
          echo "Template copied successfully"
          
      - name: Set created_at timestamp
        run: echo "CREATED_AT=$(date +%s)" >> $GITHUB_ENV

      - name: Run Terragrunt Apply
        run: |
          cd live/ephemeral/sandbox/requests/${{ github.event.inputs.request_id }}
          terragrunt run --all workspace new $REQUEST_ID || true
          terragrunt run --all workspace select $REQUEST_ID
          echo "y" | terragrunt run --all apply -- -auto-approve 

     
      - name: Store sandbox metadata in DynamoDB
        run: |

          TABLE="ukesh-table"

          REQUEST_ID="${{ github.event.inputs.request_id }}"
          OWNER="${{ github.event.inputs.owner }}"
          TTL_SECONDS="${{ github.event.inputs.ttl_seconds }}"
          CREATED_AT="${{ env.CREATED_AT }}"
          EXPIRES_AT=$((CREATED_AT + TTL_SECONDS))

          PATH="live/ephemeral/sandbox/requests/$REQUEST_ID"

          aws dynamodb put-item \
            --table-name $TABLE \
            --item "{
              \"LockID\": {\"S\": \"$REQUEST_ID\"},
              \"owner\": {\"S\": \"$OWNER\"},
              \"status\": {\"S\": \"active\"},
              \"created_at\": {\"N\": \"$CREATED_AT\"},
              \"expires_at\": {\"N\": \"$EXPIRES_AT\"},
              \"path\": {\"S\": \"$PATH\"}
            }"